version: '3'
services:

  #MySQL Service
  mysql:
    container_name: tppt_mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: tppt
      MYSQL_ROOT_PASSWORD: strong-password
    networks:
      - app-network

  #PHP Service
  php8:
    container_name: tppt_php8
    build:
      context: .
      dockerfile: docker/php8/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #PHP Service
  php74:
    container_name: tppt_php74
    build:
      context: .
      dockerfile: docker/php74/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  tppt_mysql:
  dbdata:
    driver: local
